### PR TITLE
wip: cleanup and parameterize usart

### PR DESCRIPTION
**Pull request by xoviat**
this should be the final PR to cleanup and finalize the usart interface, and to make it available for a broad range of mcus.

### CODE REVIEW

**Comment by xoviat** [comment]
@eupn Does this interface work for you? See the examples.

**Comment by Dirbaio** [comment]
@xoviat Do you think it's possible to do this with generics instead of macros? Something like the `Instance` trait in the nrf drivers. You could use associated types to force that USARTx must take DMAy CHANNELz etc.

**Comment by Dirbaio** [comment]
Maybe it's possible to use the DMASet trait, to use the DMA map from stm32f4-hal, instead of having to write it again.

 https://github.com/stm32-rs/stm32f4xx-hal/blob/2dc427733e616209362face2b75bf8a872f737e4/src/dma/traits.rs#L313

**Comment by eupn** [comment]
> @eupn Does this interface work for you? See the example.

My target chip is stm32wb55, I can’t verify this to work on that MCU yet. I’m looking for embassy on that MCU and want to try it out after looking at stm32-related foundation that you’re laying out.

**Pull request closed without merging**
