### PR TITLE
wip: add sync primatives

### LINKED ISSUE #29: add async_channel
Need an embedded verison: https://github.com/smol-rs/async-channel

### LINKED ISSUE #30: Add Mutex
A no_std version of [tokio mutex](https://tokio-rs.github.io/tokio/doc/tokio/sync/struct.Mutex.html), [async-std mutex](https://docs.rs/async-std/1.9.0/async_std/sync/struct.Mutex.html). Similar to [this mutex](https://github.com/rust-embedded-community/async-on-embedded/blob/master/async-embedded/src/unsync/mutex.rs).

### PR DESCRIPTION
**Pull request by xoviat**
fixes #29 
fixes #30 

wip

### CODE REVIEW

**Comment by xoviat** [comment]
note: with the oneshot channel, the channel is allocated on the heap. to avoid this, we will copy the stm32f4 'serial' implementation' that that splits the halves, but we will require the channel to be 'static.

**Comment by xoviat** [comment]
@eupn The plan is for channels to have a `'static` lifetime. Is this okay?

**Comment by Dirbaio** [comment]
Channels from `futures_intrusive` don't require `'static` nor `alloc`. IMO if we're going to add a channel to embassy it should be at least as good, otherwise we should just tell users to use `futures_intrusive`.

**Comment by xoviat** [comment]
I don't want to do more work than I have to. @eupn what is your opinion on this?

**Comment by xoviat** [comment]
I'm going to close this.

**Pull request closed without merging**
