### PR TITLE
Add STM timer

### PR DESCRIPTION
**Pull request by thalesfragoso**
Based on the nRF implementation

### CODE REVIEW

**Comment by Dirbaio** [comment]
Nice!

The name "RTC" is a bit confusing because it's something else in stm32. Maybe it should be named Timer? Or maybe Clock (we'd rename it to Clock on embassy-nrf too then)

**Comment by thalesfragoso** [comment]
Yeah, I think a rename would be good. I'm not good at picking names though, both Timer and Clock seem okay.

**Comment by Dirbaio** [comment]
Maybe 
- in `embassy`: Clock (the trait)
- in `embassy-stm32f4`: TimerClock
- in `embassy-nrf`: RtcClock (and TimerClock if we ever implement a clock using a Timer so there's more precision?)

**Comment by thalesfragoso** [comment]
Marking this as ready for review. I changed the default micro variant in the examples to the stm32f401, given the popularity of the black pill, but I can change it back if requested.

**Comment by Dirbaio** [comment]
:tada:

**Pull request merged**
