### PR TITLE
impl. draft rtc trait

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by Dirbaio** [comment]
I'm not sure about the RealTimeClock trait:

- `next_alarm` requires `&'static mut`, so you can't call it two times on the same RTC.
- `new_from_rtc` requires `&'static mut`, so you can't create two executors with the same RTC.

Aside from that, I think `Clock` and `Alarm` are different "concepts", so merging them in a single trait is not ideal. In both nrf and stm32 it happens that you can implement both with the same peripheral (RTC/TIMER), but this is not necessarily true in all hardware. For example, in chips that have only one compare channel per timer, you will need two TIMER peripherals to create two alarms. In that case they wouldn't be in the same peripheral at all, so it's not clear how would that chip implement the RealTimeClock trait.

**Comment by xoviat** [comment]
what if we were to have a trait called `AlarmProvider` that provides the alarms, and what if we stored the alarms inside of the executor.

example:
```
let rtc = RTC()
let executor = Executor<Alarm>::new_from_alarm(&rtc, &'static rtc);
```

This way would still be cleaner than the current situation, and would allow splitting up the functionaliyt.

**Comment by Dirbaio** [comment]
The executor stores `&dyn Alarm` because it can't have generics, tasks have pointers to it: https://github.com/akiles/embassy/blob/d098952077b8fdc8426754151bb8064214a046fa/embassy/src/executor/mod.rs#L42

**Comment by xoviat** [comment]
Then, the alarm is stored in RTC with an UnsafeCell as such. It's the cleanest interface because it allows `new_from_alarm` and removes the numbered alarms.

**Comment by Dirbaio** [comment]
I am sorry, but I don't see why this is better. Yes, this is now one call (`Executor::new_from_rtc`, vs previously `time::set_clock` and `Executor::new_with_alarm`), but;

- There are now 2 ways to set the clock: `Executor::new_from_rtc` and `time::set_clock`, vs 1 previously.
- There are now 2 ways to create an executor with alarm: `Executor::new_from_rtc` and `Executor::new_with_alarm`, vs 1 previously.
- It is surprising that creating a new executor with `Executor::new_from_rtc` has the side effect of *mutating global state*. 
- How is passing an "alarm provider" to the executor better than just passing the alarm directly?
- The API checks less things at compile time: you get a panic if you call `next_alarm` too many times. RTC could have an API like `get_alarms() -> (Alarm, Alarm, Alarm)` making it obvious that it only has 3 alarms and making it impossible for the user to create 4 executors with alarms, but this is not possible with the Provider API.

**Comment by xoviat** [comment]
you're right.

**Pull request closed without merging**
